create table USER
(
  ID            INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  ACCOUNT_ID    VARCHAR(100),
  NAME          VARCHAR(50),
  TOKEN         VARCHAR(36),
  CREATE_TIME   BIGINT,
  MODIFIED_TIME BIGINT
);